// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations/CLI need a direct (non-pooled) connection — DATABASE_URL
    // is the transaction pooler the running app uses, which doesn't
    // reliably support the DDL/long-lived transactions migrations need.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
